#!/bin/bash
set -e

HELP=false
NUM_THREADS=1
VEHICLE=false
ADD_PATH=false

for ARGI; do
    UNDEFINED_ARG=$ARGI
    if [ "${ARGI}" = "--help" -o "${ARGI}" = "-h" ] ; then
        HELP=true
        UNDEFINED_ARG=""
    elif [ "${ARGI:0:2}" = "-j" ] ; then
        NUM_THREADS="${ARGI#-j*}"
        UNDEFINED_ARG=""
        START_DIRECTORY=${ARGI}
    elif [ "${ARGI}" = "--vehicle" -o "${ARGI}" = "-v" ] ; then
        VEHICLE="true"
        UNDEFINED_ARG=""
    elif [ "${ARGI}" = "--addpath" -o "${ARGI}" = "-ap" ] ; then
        ADD_PATH=true
        UNDEFINED_ARG=""
    else
        printf "Bad argument: $UNDEFINED_ARG \n"
        exit 1;
    fi
done

if $HELP ; then
    printf "Usage: build_all.sh [location] [-j4] [options]                     \n"
    printf "Options:                                                           \n"
    printf "  --vehicle, -v          install for vehicle (no gui or shore apps)\n"
    printf "  --addpath, -ap         append binary locations to path in .bashrc\n"
    exit 1;
fi

if [ ! -d libraries ] || [ ! -d core ] || [ ! -d scripts ] ; then
    printf "Must be run in code/marine directory.\n"
    exit 1
fi

START_DIRECTORY=$(pwd)

cd libraries
cmake .
make -j$NUM_THREADS

cd ../core
./build_proto.sh
if $VEHICLE ; then
    cmake -D BUILD_SHORE_APPS=OFF .
else
    cmake -D BUILD_SHORE_APPS=ON .
fi
make -j$NUM_THREADS

cd ../drivers
cmake .
make -j$NUM_THREADS

cd ../utils
if $VEHICLE ; then
    cmake -D BUILD_SHORE_APPS=OFF .
else
    cmake -D BUILD_SHORE_APPS=ON .
fi
make -j$NUM_THREADS

if $ADD_PATH ; then
    if grep -Fxq "# Automatically generated by hovergroup build_all.sh script." ~/.bashrc ; then
        echo -e "\e[93mExisting path block detected in ~/.bashrc, no modifications will be made.\e[0m"
    else
        cp ~/.bashrc ~/.bashrc.bck
        printf "\n# Automatically generated by hovergroup build_all.sh script.\n" >> ~/.bashrc
        printf "PATH=\$PATH:$START_DIRECTORY/core/bin\n" >> ~/.bashrc
        printf "PATH=\$PATH:$START_DIRECTORY/drivers/bin\n" >> ~/.bashrc
        printf "PATH=\$PATH:$START_DIRECTORY/utils/bin\n" >> ~/.bashrc
    fi
fi

echo -e "\e[93mDone.\e[0m"
